### ISSUE TITLE
Split core with lexer/parser into separate crate?

### ISSUE THREAD

**Issue by birkenfeld** [tcr/parser-c#18]
The generated parts are huge, and lead to compile times that are not too nice. I wonder if it's possible to split mostly those parts into a subcrate, so that while working on e.g. analysis the compile cycles should be much better. E.g. `parser-c-core <- parser-c`

**Comment by tcr** [comment]
I like this suggestion! I've literally had to do this with massive LALRPOP-generated files before, this is pretty similar. It will also make it easier to accomplish #17.

I assume the right arrangement is for this to live in this same repo, e.g. `parser-c-core`, `parser-c-macro`, then `parser-c` as the root.

**Comment by tcr** [comment]
@birkenfeld Probably not necessary post-Monadectomy?

**Comment by birkenfeld** [comment]
Agreed!
